# ---------------------------------------------------------------
# $Id: $
# ---------------------------------------------------------------
# @file: Makefile
# @desc: makefile for package exonerate
#
# @history:
# @+	    <Gloup> : Sept 15 : Adapted to ORG.Annot
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

include ../../config/auto.conf

PKG = hmmer-3.1b1

include $(CFGDIR)targets/package.targ

include $(CFGDIR)targets/help.targ

# bug fix
all::
	-mkdir $(PKGDIR)/userguide

