# ---------------------------------------------------------------
# @pckg: SeqUtils / V1.0 / Gloup Jan 92
#
# @file: Makefile
# @desc: makefile for Abi library
#
# @history:
# @+	    <Gloup> : Jan 96 : Created
# @+	    <Gloup> : Jul 93 : revised version
# @+	    <Gloup> : Feb 01 : Adapted to helixware
# @+	    <Gloup> : Mar 01 : Corrected <if> bug
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

include ../../config/auto.conf

OSRC    = libaabi.c

LOCLIB = libaabi.a 

include ../../config/targets/lxlib.targ

include ../../config/targets/help.targ

INCDIR	  =	../../include

