# ---------------------------------------------------------------
# @pckg: SeqUtils / V1.0 / Gloup Jan 92
#
# @file: Makefile
# @desc: makefile for Fasta /  Fasta format IO/
#
# @history:
# @+	    <Gloup> : Jan 92 : Created (Bip version)
# @+ 	    <Gloup> : Nov 97 : Standalone version
# @+	    <Gloup> : Feb 01 : Adapted to helixware
# @+	    <Gloup> : Mar 01 : Corrected <if> bug
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

include ../../../../../config/auto.conf

OSRC   = libfasta.c

LOCLIB = libfasta.a 

include ../../../../../config/targets/lxlib.targ

include ../../../../../config/targets/help.targ

INCDIR	  =	../../include

