# ---------------------------------------------------------------
# $Id: $
# ---------------------------------------------------------------
# @file: Makefile
# @desc: makefile for package exonerate
#
# @history:
# @+	    <Gloup> : Sept 15 : Adapted to ORG.Annot
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

include ../../config/auto.conf

PKG = cd-hit-v4.6.4-2015-0603

MAKEOPTIONS= openmp=no PREFIX=$(PRTPATH)/bin

include $(CFGDIR)targets/package.targ

include $(CFGDIR)targets/help.targ

