# ---------------------------------------------------------------
# $Id: $
# ---------------------------------------------------------------
# @file: Makefile
# @desc: makefile for sequtils/src
#
# @history:
# @history:
# @+	    <Gloup> : Apr 97 : Created
# @+	    <Gloup> : Mar 02 : Updated for LXxware
#
# @note: should be processed with gnu compatible make
# @note: helixware_compatible
#
# @end:
# ---------------------------------------------------------------
#

DIRS =  Abisrc   \
        Biosrc   \
        Fastasrc \
        Utilsrc

include ../config/targets/propagate.targ

include ../config/targets/help.targ

