/* ---------------------------------------------------------------- */
/* Copyright (c) Atelier de BioInformatique                         */
/* @file: fasta_io.h                                                */
/* @desc: sequence IO in fasta format / include file                */
/*                                                                  */
/* @history:                                                        */
/* @+       <Gloup> : Aug 92 : first version                        */
/* @+       <Gloup> : Nov 95 : last revised version                 */
/* ---------------------------------------------------------------- */

#ifndef _H_fasta_io

#define _H_fasta_io

/* ==================================================== */
/* Constantes                                           */
/* ==================================================== */

#define FASTA_NAMLEN  64           /* max length of seq. name       */
#define FASTA_COMLEN  512          /* max length of seq. comment    */

#define FASTA_CHAR_PER_LINE 50     /* # of chars per line in output */

/* ==================================================== */
/* Macros standards                                     */
/* ==================================================== */

#ifndef NEW
#define NEW(typ)                (typ*)malloc(sizeof(typ)) 
#define NEWN(typ, dim)          (typ*)malloc((unsigned)(dim) * sizeof(typ))
#define REALLOC(typ, ptr, dim)  (typ*)realloc((void *) (ptr), (unsigned long)(dim) * sizeof(typ))
#define FREE(ptr)               free(ptr)
#endif

/* ==================================================== */
/* Structures de donnees                                */
/* ==================================================== */

typedef struct {                          /* -- Sequence ---------------- */
        int     ok;                       /* error flag                   */
        long    length,                   /* longueur                     */
                offset,                   /* current offset               */
                bufsize;                  /* size of current seq buffer   */
        char    name[FASTA_NAMLEN+2],     /* nom                          */
                comment[FASTA_COMLEN+2],  /* commentaire                  */
                *seq;                     /* sequence                     */
} FastaSequence, *FastaSequencePtr;

/* ==================================================== */
/*  Prototypes (generated by mkproto)                   */
/* ==================================================== */

                                        /* libfasta.c   */

FastaSequencePtr NewFastaSequence   ( void );
FastaSequencePtr FreeFastaSequence  ( FastaSequencePtr seq );

int              ReadFastaSequence  ( FILE *streamin, FastaSequencePtr seq );
int              GetFastaSequence   ( FILE *streamin, FastaSequencePtr seq );
void             WriteFastaSequence ( FILE *streamou, FastaSequencePtr seq , int char_per_line );

void             RewindFastaDB      ( FILE *streamin );

#endif
